### ISSUE TITLE
Crash during loading - 1.19

### ISSUE THREAD

**Issue by sontopo** [AlexModGuy/CloudStorage#31]
Well, I'm using Citadel 1.12.7 and the latest version of cloud storage but keeps crashing during the game load, could you help me? Thanks.

[latest.log](https://github.com/Alex-the-666/CloudStorage/files/9214920/latest.log)

**Comment by sontopo** [comment]
And this the log file
[latest.log](https://github.com/Alex-the-666/CloudStorage/files/9214920/latest.log)

**Comment by Alex-the-666** [comment]
mod log says you have citadel 1.12.5.... and that cloud storage isn't installed. are you sure this is the right crash log?
