### ISSUE TITLE
1.4.0 crashes at launch

### ISSUE THREAD

**Issue by Thaumatarge** [AlexModGuy/CloudStorage#52]
Here is the latest log of Minecraft with just Forge 45.0.42, Citadel 2.3.3, and Cloud Storage 1.4.0
[latest.log](https://github.com/AlexModGuy/CloudStorage/files/11163550/latest.log)

The log says something about "ArmorDye". My guess would be that it is something related to the recipe used to colour balloons and the mixins related to that process.

**Comment by AlexModGuy** [comment]
Hotfix will be live at https://www.curseforge.com/minecraft/mc-mods/alexs-cloud-storage/files/4476735
